#pragma once
namespace MOVEMENT
{
	enum MOVEMENT_STATUS
	{
		MOVEMENT_STATUS_STOP,
		MOVEMENT_STATUS_TARGET,
		MOVEMENT_STATUS_POINT,
		MOVEMENT_STATUS_CIRCLE, 
		MOVEMENT_STATUS_REBOUND,
		MOVEMENT_STATUS_END
	};
}